language: go

go:
  - master
  
install:
  - go get github.com/railroadmanuk/random_names
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o random_names random_names.go
  - docker build -t railroadmanuk/name_gen -f Dockerfile.scratch .
